############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "/team"
weight = 2

# [[main]]
# name = "Research"
# url = "/research"
# weight = 3

[[main]]
name = "News"
url = "/news"
weight = 4

[[main]]
weight = 3
name = "Publications"
url = "/publications"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/contact"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
